update workflow

diff --git a/.github/workflows/sync-upstream.yaml b/.github/workflows/sync-upstream.yaml
--- a/.github/workflows/sync-upstream.yaml
+++ b/.github/workflows/sync-upstream.yaml
@@ -7,8 +7,8 @@ on:
   workflow_dispatch: # manually
 
 env:
-  upstream: git@github.com:williamcorsel/hassio-addons.git
-
+  FETCH_DEPTH: 10
+  PUSH: true
 
 jobs:
   upstream:
@@ -16,5 +16,32 @@ jobs:
     steps:
       - uses: actions/checkout@v4.1.0
         with:
-          fetch-depth: 10
-      - uses: imba-tjd/rebase-upstream-action@0.5
+          fetch-depth: ${{ env.FETCH_DEPTH }}
+      - run: |
+          set -ex;
+  
+          UPSTREAM=${{ env.UPSTREAM }};
+          if [ -z $UPSTREAM ]; then
+              UPSTREAM=$(gh api repos/:owner/:repo --jq .parent.full_name);
+              if [ -z $UPSTREAM ]; then echo "Can't find upstream" >&2 && exit 1; fi;
+          fi;
+          if [ ! $(echo $UPSTREAM | egrep '^(http|git@)') ]; then
+              UPSTREAM=https://github.com/$UPSTREAM.git
+          fi;
+          if [ ${{ env.FETCH_DEPTH }} -ne 0 ]; then
+              DEPTH=--depth=${{ env.FETCH_DEPTH }}
+          fi;
+  
+          git remote add upstream $UPSTREAM;
+  
+          git fetch upstream main $DEPTH;
+  
+          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
+          git config --local user.name  "GitHub Actions";
+  
+          git rebase upstream/main;
+  
+          if [ "${{ env.PUSH }}" = "true" -a "$(git status | grep diverged)" ]; then
+              git push origin $(git branch --show-current) --force-with-lease;
+          fi;
+        shell: bash
